### ISSUE TITLE
Add knative-eventing-extension to "experimental" repo

### ISSUE THREAD

**Issue by skaegi** [tektoncd/community#10]
I propose adding a `knative-eventing-extension` folder to the `experimental` repo. This experiment would provide maintained working code showing how Knative eventing could trigger pipeline and task runs from typical eventing sources like GitHub, GitLab, etc. 

This work will also include an extension to the Tekton dashboard so that a user can see how the various pieces fit together from code change to pipeline run to running application.

**Comment by vdemeester** [comment]
@skaegi this related to https://github.com/tektoncd/pipeline/issues/315 and https://docs.google.com/document/d/1vxFEovcLxDbypYMTAS1r6t8KCL4ltGmck266tbS1mTw right ?

**Comment by skaegi** [comment]
@vdemeester yes definitely related. In Tekton we're really interested to push on the event duck typing as we have cases where events come from both Knative eventing-sources and more direct callers too.

This experiment though is just to show how knative-eventing might be incorporated into an interesting Tekton flow.

**Comment by bobcatfish** [comment]
:+1: from me! Watch this space for some more guidelines around what we'd expect to see in the dir :D (and for all the missing community docs @_@)

**Comment by vdemeester** [comment]
:+1: for me too btw :wink:

**Comment by dlorenc** [comment]
This has two thumbs up and got created. I'll close this out for now.
