### ISSUE TITLE
Links result in 404 errors under Contribution Process

### ISSUE THREAD

**Issue by maryfrances01** [tektoncd/community#1016]
From this URL:
https://tekton.dev/community/  

->  under Contribution Process, the following links result in 404:
- Find something to work on
- Propose new features
- Contribution Ladder
- Pull request review
- Propose new projects

 404: The 'tektoncd/community' repository doesn't contain the 'process.md' path in 'main'.

**Comment by krisan** [comment]
Hi, I am interested to work on the task.
