### ISSUE TITLE
Link commit message with PR url after merging into main branch

### ISSUE THREAD

**Issue by xinnjie** [tektoncd/community#1037]
### Feature request
Add PR url to  commit message  after the pr merging into main branch. 

### Use case
* PR description and discuss below often have information about the code change than commit message itself, it should be helpful if there is PR url  appended in commit message.

**Comment by AlanGreene** [comment]
Hi @xinnjie, thanks for the suggestion.

GitHub already provides a link to the PR when viewing the commit. Take the latest commit in this repo for example: https://github.com/tektoncd/community/commit/384b10bedd3a1c5fef3fdecb68e6b5444e533b19

![image](https://github.com/tektoncd/community/assets/2829095/bdaca3a9-e517-4f43-ba57-ddd47e147eff)

You can click on the highlighted link to navigate directly to the PR.

Many editors also support displaying this information either natively or with extensions, for example GitLens in Visual Studio Code displays this in 2 ways:
- inline on the selected line of code
  <img width="1193" alt="image" src="https://github.com/tektoncd/community/assets/2829095/e7beed4f-c4ab-4a98-ad13-654340e30828">
- in a more detailed tooltip on hover with multiple links to the PR
  <img width="1051" alt="image" src="https://github.com/tektoncd/community/assets/2829095/298dc7c2-39d4-400e-a515-d46b08226f9a">

Another point to consider is that modifying the commit message would break commit signing, this means that commits from contributors who sign their commits would no longer be 'verified'.

**Comment by xinnjie** [comment]
Oh thanks. It is very helpful.
