### ISSUE TITLE
Hacktoberfest 2023 Planning

### ISSUE THREAD

**Issue by wlynch** [tektoncd/community#1048]
This issue is tracking general sub-project interest for [Hacktoberfest](https://hacktoberfest.com/) 2023.

We've been asked by the CDF if Tekton is interesting in participating in Hacktoberfest this October. We need sub-project maintainer support to make this happen!

If you are a sub-project maintainer, please let us know your project is interested in participating in Hacktoberfest this year, along with a primary point of contact for your sub-project that will help with organizing. (feel free to organize multiple projects if you are a maintainer on each)

### Sub-project organizer responsibilities

- Triaging and promoting good self-contained first issues that would be appropriate for a new contributor to work.
- Making sure that CONTRIBUTING.md and other developer documentation is up to date.
- Answering questions and handling reviews from new contributors that may be interested.

The sub-project organizer does not need to do everything themselves! Feel free to delegate amongst other maintainers.

See [Jenkin's 2022 Hacktoberfest page](https://www.jenkins.io/events/hacktoberfest/) as an example for what we're aiming for.

### Timelines

- August 18th: deadline for sub-project participation (e.g. responding to this issue)
- August 31st: Tekton's deadline for letting CDF know if we're participating.
- September 15th: Have projects + issues ready to go for people to work on.
- September 29th: Deadline for Tekton Hacktoberfest blog post
- October 1st: Hacktoberfest begins!

### Project Organizers

Repo | Contact | Participating
-- | -- | --
catlin |  | ❌  
catalog |  | ❌ 
chains |  | ❌ 
cli |  | ❌ 
dashboard |  | ❌ 
hub |  | ❌ 
operator |  | ❌ 
pipeline | @afrittoli  | ✅  
results | @adambkaplan  | ✅  
triggers |  | ❌ 
website |  | ❌ 

/cc @tektoncd/catlin-maintainers @tektoncd/catalog-maintainers @tektoncd/chains-maintainers @tektoncd/cli-maintainers @tektoncd/dashboard-maintainers @tektoncd/hub-maintainers @tektoncd/operator-maintainers @tektoncd/core-maintainers @tektoncd/triggers-maintainers @tektoncd/website-maintainers

(I think I got all of the projects, but if I missed one let me know!)

**Comment by khrm** [comment]
I think results and Triggers both can benefit from this. 
Atm, maintainers of Triggers are busy with other work and there are a lot of good-first issues which people can take up.

**Comment by khrm** [comment]
@wlynch I think you missed @tektoncd/website-maintainers .

**Comment by savitaashture** [comment]
How about Operator as we don't have any outside contributors other than RedHat

**Comment by wlynch** [comment]
@khrm / @savitaashture - would you be willing to be the primary point of contact for those respective sub-projects (@khrm -> triggers, results | @savitaashture -> operator)?

**Comment by vdemeester** [comment]
I think it would make sense for a least both cli and pipeline to be part of this as well.
cc @lbernick @JeromeJu @afrittoli @jerop for pipeline
cc @piyush-garg @pratap0007 @PuneetPunamiya for cli

**Comment by adambkaplan** [comment]
Results project is in!

cc @enarha @sayan-biswas @avinal @khrm

**Comment by afrittoli** [comment]
> I think it would make sense for a least both cli and pipeline to be part of this as well. cc @lbernick @JeromeJu @afrittoli @jerop for pipeline cc @piyush-garg @pratap0007 @PuneetPunamiya for cli

Yes, I'd be happy to support pipeline participation.

**Comment by wlynch** [comment]
Reminder we are looking for responses by Friday! 🙏
