### ISSUE TITLE
make Tekton Results WG meeting for Europe + Asia  weekly

### ISSUE THREAD

**Issue by avinal** [tektoncd/community#1057]
## Background

Since US + EU meeting was closed due to low attendance. We are currently having a biweekly meeting. 

## Current
Recently, there has been a bump in the number of regular attendees as well as topics to discuss due to increased activity in Tekton Results. The development is taking pace and a biweekly 30-min call is not able to meet the need.

## Proposal

As discussed in the WG call of Aug 17th, we [agreed](https://docs.google.com/document/d/1GXKq-tc4oJUHdjIe-usHclugVU06sljo4i8BT2OaHbY/edit#heading=h.t712v4wlun20) on making the Europe + Asia call weekly.

**Comment by khrm** [comment]
@wlynch Can you setup it up?

**Comment by wlynch** [comment]
Done! (note that this has you conflicting w/ the EU productivity WG)
