### ISSUE TITLE
Add more and relevant topics to repositories

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/community#107]
The GitHub topics may be a great way to discover e.g. Tekton Pipelines. E.g. [continuous-integration](https://github.com/topics/continuous-integration) is a good way to list popular CI-systems. We should add more and relevant topics to our repositories.

Proposed topic additions to Pipelines repository:

- `[continuous-integration]`
- `[continuous-delivery]`
- `[continuous-deployment]`
- `[devops]`
- `[gitops]`

**Comment by bobcatfish** [comment]
/reopen
/remove-lifecycle rotten

This is pretty easy to do for someone with the right access, if a bit tedious!
