### ISSUE TITLE
Proposal: Tekton Supply Chain Security Project

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/community#110]
The full proposal text is outlined here: https://docs.google.com/document/d/1dJjNTOXsT_dMZIX4i5iRw10fRQZBQqUP8YmbN2AwhAA/edit#

(shared with tekton-dev)

I'd like to discuss this in the June 3rd community meeting.

**Comment by bobcatfish** [comment]
I'm very excited about this! 👍 from me

**Comment by skaegi** [comment]
@dlorenc I'm not sure why but I cannot access the above link... I believe I'm setup correctly.

**Comment by vdemeester** [comment]
I think @dlorenc did not share it *yet* with `tekton-dev@gogglegroups.com` :sweat_smile:

**Comment by dlorenc** [comment]
Sorry, it should be shared now...

**Comment by vdemeester** [comment]
Sounds good to me :+1:

**Comment by dlorenc** [comment]
Thanks! Closing since this was approved.

**Comment by bobcatfish** [comment]
hey @dlorenc, @afrittoli had a couple of follow up comments in the #governance chat:

> I reviewed both documents, I’ve got a few questions here and there but in general it makes sense to me.
I would usually prefer going through an experimental or a prototype in a personal repo.
I’ve seen that https://github.com/dlorenc/chains exists - so I wonder if that is something that could be presented / demoed to the community? Perhaps @Dan Lorenc already did present it and I missed it

**Comment by afrittoli** [comment]
What I was looking for was the background for the decision of having this as a dedicated project in its own repo. It sounds like.a reasonable approach, I just wanted to understand if there was some more context worth sharing.
Let's go ahead with this, and we can further document design decision along the way.
