### ISSUE TITLE
[Voting Open] Tekton Community Awards 2024 🏆 

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/community#1127]
This issue is to receive nominations for the 2024 Tekton Community Awards. 

Award | Description
-- | --
Most Valuable Contributor | This award recognises excellence of contributions to the Tekton project, which may be any or a combination of contributions to the project code, documentation, and infrastructure as well as advocacy and fostering adoption.
Most Valuable Advocate | This award is presented to an individual who has helped advocate for Tekton through organization of events in-person or online events, blog posts, etc.
Security MVP | This award is presented to an individual most consistently providing excellent security reports or resolving security issues.

To nominate someone, please use the linked Google form: https://forms.gle/MAuFWsA8qkwUtkR99
If you'd prefer to not use a Google form, please send an email to [tekton-nominations@googlegroups.com](mailto:tekton-nominations@googlegroups.com) including:

1. Full name or GitHub username of the person you’re nominating
2. Short description of their contributions to Tekton and why they should win.

Timeline:
- Nominations close: Thursday, February 22 at 11:59 PST
- Voting opens: Thursday, February 22
- Voting closes: Friday, March 22 at 11:59 PST
- Winners announced at [cdCon](https://cd.foundation/cdcon-2024/): April 16–18, 2024

More details are available here https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md

**Comment by vdemeester** [comment]
@afrittoli were the "winners" announced ?
