### ISSUE TITLE
Proposal: Tekton Generators

### ISSUE THREAD

**Issue by wlynch** [tektoncd/community#125]
Proposal for creating tektoncd/experimental/generators.

This project was proposed with verbal support at the [Tekton API WG on May 11th 2020](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.jkcnfusf6irl).

## The problem the project will solve

Help users bootstrap pipelines in a configurable way. This is intended to be an experimental project to explore a DSL / configuration option in parallel to other efforts like D2iQ's DSL, that stays closer to the original Tekton Pipeline/Task spec.

Pipeline Issue: https://github.com/tektoncd/pipeline/issues/2590

## Who will own it
- @wlynch 
- @dibyom 
- @YolandaDu1997 

/cc @bobcatfish @ImJasonH

**Comment by bobcatfish** [comment]
lgtm!

@afrittoli @vdemeester @abayer @ImJasonH could we have another governing board member weigh in?

**Comment by vdemeester** [comment]
lgtm :wink: I think it is very good to explore this field as it should be important for driving adoption :upside_down_face:

**Comment by wlynch** [comment]
https://github.com/tektoncd/experimental/pull/558 is ready for approval!

If you want us to split the folder creation / owners into a different commit just let us know.

**Comment by wlynch** [comment]
PR has been merged. Thanks all! :)
