### ISSUE TITLE
Create .github repository

### ISSUE THREAD

**Issue by wlynch** [tektoncd/community#129]
GitHub allows for the creation of a `.github` repository for defining default config files for common community files (CONTRIBUTING, CODE_OF_CONDUCT, issue templates, etc). https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

It'd be great to have the repo to centralize common files, and provide useful defaults for issue templates (e.g. bug, feature request, question).

My reading of the docs is that these are defaults, and individual projects would be free to override these if they wanted.

**Comment by vdemeester** [comment]
I am +:100: on this :wink:

**Comment by bobcatfish** [comment]
Let's do it!!

**Comment by wlynch** [comment]
Circling back on this. Can an org admin create this repo? Thanks!

**Comment by vdemeester** [comment]
@wlynch https://github.com/tektoncd/.github has been created :wink:

**Comment by wlynch** [comment]
Thanks!
