### ISSUE TITLE
Add catalog to experimental repository (or on its own)

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/community#13]
I propose adding a `catalog` folder to the `experimental` repo. This experiment would provide maintained task and pipeline definition for people to use in their Tekton Pipeline instances. This would act the same as [`knative/build-templates`](https://github.com/knative/build-templates) but for Tekton objects

Each "definitions" (template, pipeline) would be in a separate directory along with a README.md and a Kubernetes manifest, so you can choose which to install on your cluster.

cc @bobcatfish

**Comment by siamaksade** [comment]
It might make sense to have both `experimental/catalog` and `catalog` so that tasks are introduced in the experimental repo and are graduated to the _catalog_.

**Comment by dlorenc** [comment]
I like the pattern from helm/charts where there's a single repo with multiple "levels" of support.

**Comment by vdemeester** [comment]
@dlorenc that would make sense to me too (and I kinda like that :angel:)

**Comment by dlorenc** [comment]
OK, let's go for it then. Who will be the intiial OWNERS? I'll be one. @kimsterv wants to as well.

**Comment by vdemeester** [comment]
I can be one too :angel: :pray:

**Comment by dlorenc** [comment]
OK, three is enough for now!
