### ISSUE TITLE
Question: Policies for getting edit access to Project tab?

### ISSUE THREAD

**Issue by wlynch** [tektoncd/community#138]
/kind question

Is there any process in place for getting edit access to the projects tab for project management? I'd like to get access in experimental for myself and @dibyom so we can manage project pages for the `results` and `generators` projects.

Thanks!

**Comment by vdemeester** [comment]
As far as I know, there is no dedicated permissions for projects, so to gain "edit access" to the project tab, you need to get edit access to the project, which means the requirement are the same as being an OWNER :sweat_smile:
