### ISSUE TITLE
Production readiness checklist in TEP?

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/community#164]
The KEP process includes a very thorough production readiness checklist (thanks @mattmoor !):

https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/README.md#production-readiness-review-questionnaire
 
Probably worth looking at these one at a time and seeing if any translate over - however @vdemeester maybe you already did this in which case I'm happy to close this.

At first glance it looks like many of them won't exactly translate to Tekton, and maybe we can build up a list like this over time, but if there's anything we can learn from this list and just adopt let's do it!

**Comment by vdemeester** [comment]
/kind feature

> Probably worth looking at these one at a time and seeing if any translate over - however @vdemeester maybe you already did this in which case I'm happy to close this.
> 
> At first glance it looks like many of them won't exactly translate to Tekton, and maybe we can build up a list like this over time, but if there's anything we can learn from this list and just adopt let's do it!

Yep, I initially left this part out intentionnaly, but indeed we should try to build our own checklist (inspired from this one).

**Comment by bobcatfish** [comment]
I think we've been doing a good job of incrementally updating the TEP template as we go, so I'm happy to close this issue for now and we can add things as they come up?
