### ISSUE TITLE
Maintain a table of TEPs

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/community#178]
It would be nice to have a TABLE of TEPS in our docs, with at least the following details:

| number | title | state | owners |
|---------|-----|------|--------|

We should provide a script to be executed when working on TEPs. The script should:
- update the table if needed
- create a new TEP from the template with an available number 
- check that TEPs have the required header info

The same script should be used in a CI job to check if the table is up to date and the proposed changes are ok.

/kind feature

**Comment by vdemeester** [comment]
@afrittoli I even have a `teps.tekton.dev` static generated website *project* in the making (soon-ish)
Otherwise, yes I do agree, it would be nice to have a table of all the TEP, there state, …

**Comment by vdemeester** [comment]
@afrittoli I think this can be closed right ? (it's on the README of the tep folder)
/remove-lifecycle stale

**Comment by sbwsg** [comment]
Yup, this can be closed now.  The TEPs are now kept in a table visible at https://github.com/tektoncd/community/tree/main/teps kept in sync with the [teps python program](https://github.com/tektoncd/community/tree/main/teps/tools).
