### ISSUE TITLE
Add guidance to help folks with Hacktoberfest 2020 here

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/community#188]
Hey everyone, I've been doing things with the cd.foundation's outreach commitee and we've been discussing Hacktoberfest and how Jenkins did it in the past, see https://www.jenkins.io/events/hacktoberfest/

I think it'd be a good opportunity to encourage folks to contribute to Tekton as part of Hacktoberfest and so I've been thinking of putting together some documentation - we could tell people which labels to use, who are handy contacts if they get stuck, and who are the awesome mentors/contacts to have.

As a start it could be something like added here into the readme at the top (so under, say, hacktoberfest-2020.md which we link to)...

@eddycharly on our recent Dashboard Working Group call suggested we do things a little more personable too as opposed to just some text - so a link to a short introductory video may be of use, as well as a mention of the project ideas we have for each area.

For project areas I'm thinking...
- Dashboard
- Pipeline
- CLI
- Catalog
- Website
- Experimental

Operator and Chains? Not sure about the learning curve here, unfamiliar with contributing to either, so could do with some experts.

Tagging @abayer @vdemeester @bobcatfish @eddycharly @dibyom @afrittoli @AlanGreene for input especially, should anyone want to share ideas on how to best go about it.

Please share this as well with anyone else you think can pitch in, thanks!

P.S, for the Dashboard we've got this so far, and this is from our most recent working group call.

Hacktoberfest
- Docs / website / katacoda enhancements
- Import
  -  from catalog by version?
   - kubectl apply doesn’t work with generateName (needs to be a create) which is used in a lot of examples in the pipeline repo, so should the action be customisable or use a different method to import the resources https://github.com/tektoncd/dashboard/issues/1552
  - Support git revision https://github.com/tektoncd/dashboard/issues/1550
- Workspaces not supported for TaskRuns and PIpelineRuns https://github.com/tektoncd/dashboard/issues/1283
- Anything for chains? Looks like no CRDs
- Single namespace install revisit (docs) https://github.com/tektoncd/dashboard/issues/1018 and https://github.com/tektoncd/dashboard/issues/1507
- Security revisit (anything preventing adoption)
- Platform support (e.g. clouds) - try and doc
- Any links/common themes to the other Tekton project areas?
- Update roadmap with progress to date / changes in approach etc.

**Comment by AlanGreene** [comment]
I think it's safe to close this one now 😸 

/close
