### ISSUE TITLE
Very serious question...

### ISSUE THREAD

**Issue by inductor** [tektoncd/community#190]
What animal are the Tekton Friends?

**Comment by chmouel** [comment]
I believe it's a cat

**Comment by inductor** [comment]
@chmouel Yeah, but they kinda look like Tanuki(Japanese raccoons) or foxes :|

![image](https://user-images.githubusercontent.com/20236173/91716464-ac02b080-ebca-11ea-9164-757c7997a253.png)

**Comment by bobcatfish** [comment]
if we can work a tanuki in somewhere I am all for it :D

![image](https://user-images.githubusercontent.com/432502/91726592-8647be00-eb6e-11ea-9300-40a7c5b50e95.png)

From the left: dog, cat, rabbit :D
