### ISSUE TITLE
Is there any other requirement to be listed the rankings?

### ISSUE THREAD

**Issue by kobaji** [tektoncd/community#209]
Hi there, hope this issue is appropriate.

# What I hope

I would like my contribution to Tekton to be listed in the following Tekton rankings:
  - https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1&var-period_name=Last%20month&var-metric=contributions
  - https://www.stackalytics.com/unaffiliated?project_type=tekton-group&module=community@tekton&date=7

# What I did

I added my affiliation to [github_users.json](https://github.com/cncf/devstats/blob/master/github_users.json).
  - This is because I found I need to add my affiliation to [github_users.json](https://github.com/cncf/devstats/blob/master/github_users.json) in the `Description` of the website [ranking](https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1&var-period_name=Last%20month&var-metric=contributions).
  - And in order to add it, I need to edit [developers_affiliations2.txt](https://github.com/cncf/gitdm/blob/master/developers_affiliations2.txt), stored in [gitdm repository](https://github.com/cncf/gitdm).
      - [gitdm>README.md](https://github.com/cncf/gitdm/blob/master/README.md#addingupdating-affiliation) told it to me.

I confirmed that my affiliation has been imported to [github_users.json](https://github.com/cncf/devstats/blob/master/github_users.json).

# What I need to know

My affiliation will be listed in those rankings once I contributed to Tekton (any repositories such as community, dashboard, pipeline, etc.), right?
  - for example, this issue will be counted to the ranking?
  - Or is anything else required?

Thank you for your kind help.

**Comment by afrittoli** [comment]
Devstat configuration is hosted by the CNCF (https://github.com/cncf/devstats/tree/master/cdf) - so you may file a PR or an issue to that repo for any change that you may require. I believe the configuration is owned by CNCF too.

Stackalytics configuration is hosted by opendev https://opendev.org/x/stackalytics/src/branch/master/etc/default_data.json.
Historically the service has been owned by a single company - according to the ["about" link on www.stackalytics.com](https://wiki.openstack.org/wiki/Stackalytics) it still is. The configuration is not maintained by the Tekton community.

**Comment by kobaji** [comment]
Thanks @afrittoli , your comment is a quite helpful for me.
I'll ask CNCF what required is.

Hope my question is resolved by asking CNCF or opendev

Thank you very much again!!

**Comment by kobaji** [comment]
About Devstats, I found I just need to wait a bit.
And about Stackalytics, I don't need to find the solution right now.

Therefore I close this issue.
Thanks a lot, @afrittoli and folks!!
