### ISSUE TITLE
Tekton Slack joining link has expired

### ISSUE THREAD

**Issue by aristosvo** [tektoncd/community#21]
The [link](https://join.slack.com/t/tektoncd/shared_invite/enQtNjE4MDgwMDYxNjA3LTM5Mjc1YWQyN2FjNDhkZDU5NmNmMTZhMDkxZDE4NzE1ZjhjOWU5OTIzNDM5YmQ3NjU5OTFhYzc0M2JmYjg5Mzc) in the [contact.md](https://github.com/tektoncd/community/blob/master/contact.md#slack) to join the Slack of Tekton CD is not valid anymore

![NoLongerActive](https://user-images.githubusercontent.com/8375124/58342548-f8e8ca80-7e50-11e9-82f7-9319246e81b2.png)

**Comment by bobcatfish** [comment]
Thanks for reporting this @aristosvo !! I've got #23 open to fix the link in the docs but in the meantime here it is directly: https://join.slack.com/t/tektoncd/shared_invite/enQtNjQ1NjQzNTQ3MDQwLWViNmMxYTI2ZDliMTAzZjAwNzM1OWQ4NzUwMTUzNWY3YTNlZTU4NmQyOGMwZTlmY2I5ODAzYzNmMDdiZDdjYjA

Let me know if that doesn't work for you!

**Comment by hunner** [comment]
Hello, it seems to have expired again.

**Comment by popcor255** [comment]
It has seemed to have expired again.

**Comment by ywluogg** [comment]
The link is still inactive

**Comment by bobcatfish** [comment]
@ywluogg i think you were able to get it working in the end, right? i.e. the link added in https://github.com/tektoncd/community/pull/23 is working?

**Comment by ywluogg** [comment]
Yes verified the link in the code is working
