### ISSUE TITLE
Add TektonCD User Profiles

### ISSUE THREAD

**Issue by xihaLong** [tektoncd/community#28]
Make it clear for whom TektonCD is intended, in order to guide future design discussion and decisions. There was a document in K8s and now in Helm useful as a template
https://github.com/helm/community/blob/master/user-profiles.md

Lets add user-profiles.md to Tekton in the community repo. Optionally have Tekton's user-profiles.md reference its inspiration in Helm

**Comment by xihaLong** [comment]
"Any substantial changes to the policies in this repo should be reviewed by at least 50% of the governing board." I will add the governing board to a pull request

**Comment by xihaLong** [comment]
I had asked earlier if there were applicable personas in Tekton. This change is aimed at sharing user profiles rather than personas, as explained in the document itself. If the committee has names to offer for example actors from each group of user type, then Tekton may consider adding a personas.md document instead

**Comment by dlorenc** [comment]
Thanks for sending this!
