### ISSUE TITLE
Could you please tell me when Tekton is planned to GA??

### ISSUE THREAD

**Issue by kobaji** [tektoncd/community#297]
Hi there, I am working for Tekton development.

Could you please tell me the about Tekton's roadmap?? Or could you please share the document about the roadmap?

Especially I'd like to know when Tekton pipeline, dashboard, cli, etc... will go GA.
Honestly I have read the document [roadmap.md](https://github.com/tektoncd/community/blob/master/roadmap.md) but I could not find out when Tekton will go GA.

Some of contributors may be wondering this, e.g. [this slack message](https://app.slack.com/client/TJ45YV83X/CJ62C1555).

N.B.

- In my understanding, once Tekton goes GA, the value of the version becomes 1.0.0 or more.
- this issue might be related with an issue #256 .

Thank you.

**Comment by vdemeester** [comment]
hey @kobaji we need to communicate more around this but, in a gist (and this is mostly *my* opinion here):

- _GA_ is usually for product, and *so far*, Tekton provides only components (not a full fledge, opiniated, product).
- This means we should most likely focus on "stable" version of tekton components, and on this, "stable" in the k8s world means providing a `v1` API. Providing a `v1` API doesn't necessarly mean the component is 1.0 ([knative](https://knative.dev) is a good example here).
  - `tektoncd/pipeline` has an issue to track work related to providing a `v1` API, see https://github.com/tektoncd/pipeline/issues/3548
  - Other components need to provide those (in the roadmap form, …)
- We also need to update the community roadmap and each component roadmap to be up-to-date with our vision

All this needs to be discussed as a community, through the mailing lists, working groups, … 😉

**Comment by kobaji** [comment]
Thanks @vdemeester I understood that Tekton's roadmap needed to be updated from [roadmap.md](https://github.com/tektoncd/community/blob/master/roadmap.md).
Thank you very much for your kind help!!

**Comment by kobaji** [comment]
Thank you @vdemeester for this issue.

I found the roadmap in tektoncd/community and tektoncd/pipeline were updated!! 
https://github.com/tektoncd/community/blob/feaba0b7f4f6f514d1771625770ef67114d8ad67/roadmap.md
https://github.com/tektoncd/pipeline/blob/93e368dbcb014e8650a6ba8ad01ca3c5f6eb6554/roadmap.md

And of course I have had a look your commits about the change of default branch from master to main (^_^)
Thanks!!
