### ISSUE TITLE
Try out github based GitHub org management

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/community#30]
## Current behaviour

Management of org membership, the teams we are using in tektoncd and who is on them, is super ad-hoc and based mostly around folks privately messaging ppl with enough power (e.g. me , @vdemeester , @dlorenc @abayer @kimsterv ) to get access to stuff. Most changes are not recorded anywhere, so none of us probably even really know what kind of changes the other folks are making XD

## Desired behaviour

Decisions like who to add to what, or what teams to create:
- Should be clearly recorded (ideally in github itself!)
- Should have an obvious path forward (e.g. how does a random new contributor know what to do to get added to the org?)

## Additional info

The folks working on Kubernetes ( + @fejta ) have created a tool called periobolos (https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos) which looks like it might do everything we need!

**Comment by dlorenc** [comment]
Plan:

- Add a peribolos config to the tektoncd/community github repo
- Add documentation for users on how to add themselves
- Run this manually for now
- Wrap peribolos in a tekton Task
- Automate the peribolos syncing

**Comment by dlorenc** [comment]
I would like to get the community PR merged first, then do some testing in the plumbing repo until it's ready, and merge that one second.

Then I can work to automate this via triggers.

**Comment by fejta** [comment]
How are things going?

**Comment by bobcatfish** [comment]
@fejta they are going amazingly so far! @dlorenc can probably give you more details but it's working exactly as intended - and is having the knock on effect of making us start thinking about and articulating the policies around when we want to actually add ppl to what ( + @vdemeester )

thanks very much for the great tool @fejta ❤️

**Comment by bobcatfish** [comment]
oh and @dlorenc we can probably resolve this issue right?
