### ISSUE TITLE
Proposal: Common Expression Language Custom Task (CELRun)

### ISSUE THREAD

**Issue by jerop** [tektoncd/community#304]
Proposal for creating **tektoncd/experimental/cel** to incubate **Common Expression Language Custom Tasks** project

Per [process](https://github.com/tektoncd/community/blob/master/process.md#proposing-projects), this project was proposed with verbal support at the [Tekton WG on Jan 13th 2021](https://docs.google.com/document/d/1rPR7m1Oj0ip3bpd_bcS1sjZyPgGi_g9asF5YrExeESc/edit)

## The problem the project will solve

CEL Custom Tasks will allow us to experiment with CEL in Tekton Pipelines without adding CEL directly to the Tekton API surface

CEL Custom Tasks would be useful in evaluating more complex expressions for guarding execution of Tasks beyond what we support in WhenExpressions, [read more](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#celrun-custom-task)

Related issues: 
- https://github.com/tektoncd/pipeline/issues/3149
- https://github.com/tektoncd/pipeline/issues/2812
- https://github.com/tektoncd/pipeline/issues/2219
- https://github.com/tektoncd/pipeline/issues/2127
- https://github.com/tektoncd/pipeline/issues/1393

## Who will own it
- @jerop 
- @bobcatfish 
- @pritidesai 
- @ImJasonH 
- @bigkevmcd 

## Updates
- Project: https://github.com/tektoncd/experimental/tree/master/cel
- TEP: https://github.com/tektoncd/community/pull/314

/cc Governing Board: @abayer @vdemeester @bobcatfish @afrittoli @ImJasonH

**Comment by afrittoli** [comment]
+100

This would be useful to simplify how we use conditions today in dogfooding, so I'd be happy to start running the custom task controller in dogfooding from the experimental repo.

**Comment by ImJasonH** [comment]
+1, happy to co-own and help update and contribute [cel-task](https://github.com/imjasonh/cel-task) as a base (or start from scratch if that's better).

🎉

**Comment by jerop** [comment]
> +1, happy to co-own and help update and contribute [cel-task](https://github.com/imjasonh/cel-task) as a base (or start from scratch if that's better).

yes yes, we can build on it, thanks for your contributions @ImJasonH!

some changes I propose we make include:
- when the CEL expression is valid and is evaluated successfully, the `ConditionSucceeded` in status of the CELRun is set to `True` regardless of the expression evaluation result and the CELRun produces a `Result` representing the expression evaluation result
- when the CEL expression is invalid or any other error is encountered, the `ConditionSucceeded` in status of the CELRun is set to `False`

this will allow us to distinguish between errors and the expression evaluating to false, which was one of the issues with `Conditions`

**Comment by ImJasonH** [comment]
> some changes I propose we make include:

Yeah those both sound like good improvements. 👍

**Comment by jerop** [comment]
thanks for the quick review @ImJasonH and @afrittoli 

created the project folder in https://github.com/tektoncd/experimental/pull/691

**Comment by jerop** [comment]
Common Expression Language Custom Tasks is available in https://github.com/tektoncd/experimental/tree/master/cel
