### ISSUE TITLE
Proposal: Pipelines in Pipelines Custom Tasks

### ISSUE THREAD

**Issue by jerop** [tektoncd/community#330]
Proposal for creating **tektoncd/experimental/pipelines-in-pipelines** to incubate Pipelines in Pipelines project

Per [process](https://github.com/tektoncd/community/blob/master/process.md#proposing-projects), this project was proposed with verbal support at the [Tekton API WG on Feb 1st 2021](hhttps://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#)

## The problem the project will solve

The project would enable users to specify in `Pipelines` how to create and run `PipelineRuns`, similarly to `TaskRun`s, as further described in [this issue](https://github.com/tektoncd/pipeline/issues/2134). 

One use case is providing a set of `Tasks` as a complete unit of execution, as demonstrated by an example @madbence shared in https://github.com/tektoncd/pipeline/issues/2134#issuecomment-631552148:

"This feature would be really useful for us. eg. right now we have a task that can set the status on a given commit, and a task that can execute unit tests (eg. `run npm` test, etc.). We'd like to distribute a task/pipeline that can combine these (eg. set the commit to pending, run unit tests, set commit status to success/failure)".

![image](https://user-images.githubusercontent.com/18076400/106499761-fb594f80-648e-11eb-9439-40b1f8baab19.png)

"We'd like to provide to option to use `set-status` and `run-unit-tests` in a pipeline, and to be able to use a "higher-level" task, like `run-unit-tests-with-commit-status`".

Other use cases are discussed in [doc](https://docs.google.com/document/d/14Uf7XQEnkMFBpNYRZiwo4dwRfW6do--m3yPhXHx4ybk/edit#heading=h.lycmm34yprtj) and will be explored further in a [TEP](https://github.com/tektoncd/community/tree/master/teps). 

**Prototype**: https://github.com/jerop/experimental/tree/piprun/pipelines-in-pipelines
**Issue**: https://github.com/tektoncd/pipeline/issues/2134

## Who will own it
- @jerop 
- @bobcatfish 
- @ImJasonH 
- @afrittoli 

/cc @abayer @vdemeester @bobcatfish @afrittoli @ImJasonH (Governing Board)

**Comment by afrittoli** [comment]
Thanks you for this proposal, I think this is a really good idea, it helps a lot breaking down pipelines and boosts the pipeline reusability. 

The idea of a "unit of execution" in the use case above is inline with pipeline reusability. 
In the diagram above, we could use the pipeline finally capability to ensure the last update is always executed.

**Comment by vdemeester** [comment]
Thanks for this proposal @jerop. I 💯 % vote for experimenting on this, thus **I approve** 😛

**Comment by ImJasonH** [comment]
I approve of this effort. 👍 

In fact I'm really excited about it! 🎉

**Comment by jerop** [comment]
/lifecycle frozen

actively working on this project as described in [TEP-0056: Pipelines in Pipelines](https://github.com/tektoncd/community/blob/main/teps/0056-pipelines-in-pipelines.md)

**Comment by bobcatfish** [comment]
@jerop i feel like since we have the experimental project we could probably close this specific issue? or did you want to keep it open for tracking?

**Comment by jerop** [comment]
sure, we can close it - can track the ongoing work in the experimental repo
