### ISSUE TITLE
 Project Proposal: Tekton Brew repository 🍻

### ISSUE THREAD

**Issue by chmouel** [tektoncd/community#40]
This issue is is to track the proposal to create a new repository called `homebrew-tektoncd`. 

The repository will be storing homebrew `formulas` of the different tekton projects starting with the [cli](https://github.com/tektoncd/cli).

# Background

Homebrew is a popular package manager to install softwares on OSX 

Brew offers [a way](https://docs.brew.sh/Taps) for projects to provide their own thrid-party repositories which is called `taps`. The way the taps work is  by a naming convention with an homebrew- prefixed repository in the project github organisation. 

For example having a repository called `homebrew-tektoncd` in the tektoncd github org will allow users to simply add the `tap` with : 

```
brew tap tektoncd/tektoncd
```

You can then have multiple formulas in there like `tektoncd-cli`, which  the user can install with : 

```
brew install tektoncd-cli
```

# Example

I have a personal brew repository for `tektoncd-cli` located here : 

https://github.com/chmouel/homebrew-tektoncd-cli/

which has been succesfully used for the last few cli releases to provide an easy way to install tektoncd-cli 

# Maintainers

I and @vdemeester will be maintaining it.

 Since we are using `goreleaser` [brew plugin](https://goreleaser.com/homebrew/) (for at least the cli) to automatically update the formulas when releasing there should be very minimal maintainance.

# Related

* https://github.com/tektoncd/plumbing/issues/43
* https://github.com/Homebrew/homebrew-core/pull/43360
* https://github.com/tektoncd/cli/issues/99

**Comment by bobcatfish** [comment]
![image](https://user-images.githubusercontent.com/432502/65971502-447e3700-e436-11e9-9646-0a1ef0e46bc8.png)

**Comment by ahpook** [comment]
👍 I'd be happy to help maintain formulae too! I own a similar tap repo at https://github.com/lyraproj/homebrew-lyra

**Comment by vdemeester** [comment]
https://github.com/tektoncd/homebrew-tools is live :tada: 
Went for `homebrew-tools` because it feels better to do `brew tap tektoncd/tools` than `brew tap tektoncd/tektoncd` :stuck_out_tongue_closed_eyes: 

/close
