### ISSUE TITLE
Recording working group meetings: better and more automated

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/community#44]
At the moment, all of the working groups are recording via youtube and end up in my personal inbox (because i own the calendar maybe? I dont even know). This means:

* I am the only one who has access to them until I upload them to [the shared drive](https://github.com/tektoncd/community/blob/master/contact.md#shared-drive)
* If i go on vacation or get behind, no one can see the videos!
* Also only Google employees can start recording the calls

So we should:
* Find a way to record videos that can be initiated by non-Google folks too (maybe zoom? might need budget help here from the CDF)
* Add automation (maybe with Tekton??) to automatically publish the videos and make them available:
  * Definitely in the shared drive
  * Maybe also in a slack notificaiton
  * Maybe somehow added to the meeting notes too

**Comment by a-roberts** [comment]
Bumping this one as something we'd like to happen especially, any thoughts/ideas?

So while there's `Find a way to record videos that can be initiated by non-Google folks too (maybe zoom? might need budget help here from the CDF)`... I've made and edited videos in the past using Davinci Resolve and OBS Studio; both available for free. These were for personal use, but surely there's a good option that doesn't involve splashing out cash?

**Comment by vdemeester** [comment]
So, I think google meet became available for everybody to use right ? @a-roberts can you try to create a meeting using your account (IBM or personal) to see ?

**Comment by a-roberts** [comment]
> So, I think google meet became available for everybody to use right ? @a-roberts can you try to create a meeting using your account (IBM or personal) to see ?

There's no record meeting option though

```
This feature is available with the G Suite Enterprise and G Suite Enterprise for Education editions. For details, see Compare G Suite editions.
```

from https://support.google.com/meet/answer/9308681?hl=en-GB

**Comment by vdemeester** [comment]
ah sad :sweat:

**Comment by jjasghar** [comment]
Not a troll, but maybe we should create `jitsi.tekton.dev` and iirc there is a way to run it on k8s pretty easily now. ideally, @vdemeester and i are gonna spend an hour investigating.

**Comment by popcor255** [comment]
@bobcatfish Are the working group videos on youtube public? If it is can we get the channel url? If it is not, can we get the videos public? It might be easy to have a slack bot with pub/sub just link the videos to the slack channels.

**Comment by vdemeester** [comment]
> @bobcatfish Are the working group videos on youtube public? If it is can we get the channel url? If it is not, can we get the videos public? It might be easy to have a slack bot with pub/sub just link the videos to the slack channels.

@popcor255 no youtube for the working group videos. So far we do manually receive them (the user that did setup the event) and move them to the shared drive (with `tekton-dev@`), adjust permisisons & co. It is a little bit a pain (I am lagging behind, ~15 recording... :scream_cat:), but yeah we need to find a way to automate this (either with meet.google.com, zoom, jitsi, …)

**Comment by popcor255** [comment]
@vdemeester Sorry I thought it was being recorded via youtube based on the op. If there is no easy way to make the video public then the solution purposed by @jjasghar sounds promising.

> @bobcatfish Are the working group videos on youtube public? If it is can we get the channel url? If it is not, can we get the videos public? It might be easy to have a slack bot with pub/sub just link the videos to the slack channels.



> @bobcatfish Are the working group videos on youtube public? If it is can we get the channel url? If it is not, can we get the videos public? It might be easy to have a slack bot with pub/sub just link the videos to the slack channels.

@vdemeester Sorry I thought it was being recorded via youtube based on the op. If there is no easy way to make the video public then the solution purposed by @jjasghar sounds promising.

**Comment by jjasghar** [comment]
I'm doing some investigation, and i've found https://github.com/mingfang/terraform-k8s-modules/tree/master/examples/jitsi which may at least be a start to get going. Updates when I have them.

**Comment by jjasghar** [comment]
I will say there is a "direct stream to youtube too" https://jitsi.org/blog/live-streaming-with-jitsi-and-youtube/

**Comment by vdemeester** [comment]
> I will say there is a "direct stream to youtube too" https://jitsi.org/blog/live-streaming-with-jitsi-and-youtube/

Yeah I saw that one, it's very nice :stuck_out_tongue_closed_eyes:

**Comment by wlynch** [comment]
@jjasghar - I'm hesitant to setup our own video conferencing infra. I don't think this is something we want to be on the hook for when things go wrong, and we'd need to work out other things like recording and moderation. I think it's still worth looking into, but I have a bit of skepticism at the moment :)

@popcor255 WG meetings are uploaded to the Community Drive Folder - https://drive.google.com/drive/folders/1w8rv0mBwM3mJXs84C4mVLiMsZXTYOM5s?usp=sharing (anyone who is a member of tekton-dev googlegroup should be able to access)

**Comment by afrittoli** [comment]
> @jjasghar - I'm hesitant to setup our own video conferencing infra. I don't think this is something we want to be on the hook for when things go wrong, and we'd need to work out other things like recording and moderation. I think it's still worth looking into, but I have a bit of skepticism at the moment :)

I agree it wouldn't be straight forward, however the current situation is less then ideal. 
The docs WG could not meet several times because of this. 

What we would need to experiment with Jitsi/[Jibri](https://github.com/jitsi/jibri) is:
* someone to drive this work forward
* infrastructure, 1 VM to start with, not sure about the spec

**Comment by afrittoli** [comment]
There is a [self-hosting](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-start) guide, but it involves some manual work, which would be fine for initial experimentation, however eventually we would need automation.
There is a pretty new [ansible role](https://github.com/udima-university/ansible-jitsi-meet) on github which we could evaluate.

I think it would also be useful in general to collect what requirement we have for videoconferencing, for instance:
- meeting infra (https://github.com/jitsi/jitsi-meet)
- recording infra (https://github.com/jitsi/jibri)
- browser / mobile support
- authentication / users
- security

**Comment by bobcatfish** [comment]
I think this is still relevant (as someone who still has to upload videos manually tho i think @vdemeester has taken on at least half of this burden as well at this point XD)

/remove-lifecycle stale

**Comment by AlanGreene** [comment]
Still relevant. Are the CDF/LF Zoom meetings an option? Looks like they have automation for recording and publishing videos to YouTube. It would also avoid some of the permissions issues we have today that require specific people / people from specific orgs to start / record meetings.

/remove-lifecycle stale

**Comment by bobcatfish** [comment]
still relevant!

/remove-lifecycle stale

@AlanGreene I think they are - in fact i belive @afrittoli has recently gotten access to the CDF zoom account and is planning to start using it for documentation working group meetings 🤞

**Comment by AlanGreene** [comment]
Yes I spoke to him about it last week and we're going to try it for the Dashboard working group too. Looking forward to getting that running again 😸

**Comment by bobcatfish** [comment]
we're currently moving all of our recordings to zoom

**Comment by bobcatfish** [comment]
Thanks for making this happen @afrittoli !! 🎉  🎉  🎉
