### ISSUE TITLE
Tekton Dashboard Repository

### ISSUE THREAD

**Issue by skaegi** [tektoncd/community#6]
I propose work on a Tekton Dashboard similar in spirit to the Kubernetes Dashboard. In other words ... a general-purpose web UI for Tekton CD. Similar to the Kubernetes dashboard this would be an optional component that follows all changes in the Tekton CD project. Under the covers it will look similar to the Kubernetes Dashboard with a static web UI and Go back-end.

Our initial goal for the dashboard is to provide a basic UI to show execution results for Pipeline and Task runs as well as providing a view on to other involved Tekton resources in the cluster. The dashboard should be lightweight, up-to-date, and follow the Tekton CD pipeline project in terms of how's it built, managed, and released.

We'd like to do a demo to the WG but then begin work in a `tektoncd/dashboard` or `tektoncd/tekton-dashboard` repository.

**Comment by gorkem** [comment]
@skaegi are you envisioning to deliver UI components that could be reusable on any web page?

**Comment by skaegi** [comment]
Ha! @gorkem -- yes that is exactly what we've envisioning.

**Comment by skaegi** [comment]
Thanks all - `tektoncd/dashboard` created and in the process of setting things up.
