### ISSUE TITLE
TEP-0073: Simplify Metrics

### ISSUE THREAD

**Issue by lbernick** [tektoncd/community#603]
# TEP Description
One-line TEP description: Simplify metrics to improve performance and user experience
TEP: https://github.com/tektoncd/community/blob/main/teps/0073-simplify-metrics.md
Author(s): @vdemeester @yaoxiaoqi @khrm 
Project(s): Pipeline
Release Targets:

# TEP References
- [ ] TEP pull request(s):
  - #466 
- [ ] Implementation pull requests(s):
  - tektoncd/pipeline#4201

**Comment by khrm** [comment]
This was resolved by https://github.com/tektoncd/pipeline/pull/4201 pr

**Comment by lbernick** [comment]
Awesome, glad to hear it! @khrm @vdemeester @yaoxiaoqi would one of you be able to take on updating the TEP -> implemented with any details of the work done?

**Comment by khrm** [comment]
@lbernick I look into that issue. `webhook_request_latencies_bucket` metric is coming from knative/pkg. This won't be solved by this TEP.

**Comment by lbernick** [comment]
Closed by #639
