### ISSUE TITLE
New Format for Tekton WG meeting 

### ISSUE THREAD

**Issue by dibyom** [tektoncd/community#617]
This is a tracking issue for changes to the Tekton WG meeting format as discussed on the mailing list: https://groups.google.com/g/tekton-dev/c/5kSTFAG9zEQ/m/SMMNmEsLCAAJ

We decided to shift to a demo focussed meeting once a month with a weekly project status email replacing the project updates section of the meeting

- [x] Cancel old meeting Invites
- [x] First new meeting date - Feb 9
- [x] Send out calendar invites for the new meeting
- [x] Get at least 3 demos for the first meeting 
- [ ] #618
- [x] Get more facilitators
- [x] Meeting cadence - two weeks for now
    - [x]  Change calendar invites
- [x] Update Facilitator instructions with email template to send call for demos to both tekton-dev and tekton-users
- [x] send recording + feedback after meeting

**Comment by dibyom** [comment]
@afrittoli @vdemeester would you mind creating a calendar invite for the EU/Asia version of the meeting? (I don't want to do it since then a Googler will be required for the recording).
Starting Wednesday February 23, repeating every 4 weeks at 12:30PM UTC

**Comment by vdemeester** [comment]
I think it's already done 🙃 
cc @afrittoli @dibyom we probably can close

**Comment by vdemeester** [comment]
I'll go ahead and close that one. Feel free to comment if you think it shouldn't have been the case.
