### ISSUE TITLE
Craft the scope and charter of the S3C Working Group

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/community#629]
@andrea will give it the first pass
@priti

**Comment by pritidesai** [comment]
S3C WG - hoping to start working on it this week before the next WG.

**Comment by afrittoli** [comment]
Draft : https://hackmd.io/-fXxObGpRsCGjNeajgz9eA

**Comment by bobcatfish** [comment]
From [discussion in s3c working group today](https://hackmd.io/gFcAZMFMRwuTaZ1i7Y3fSg?view#Notes):
- Would like the scope to have clear links to docs with more detail on what needs to be done (already has link to brainstorming doc, maybe also the [SLSA case study doc](https://docs.google.com/document/d/12yYP0M_zz5Tc9ftGnLwhDZ_tdZBq4mEod70ngWtHmLs/edit) - and/or the milestones (https://github.com/orgs/tektoncd/projects/19/views/8) ?
- Would like the scope doc to be clear around whether it is proposing a new project (e.g. with its own repo) or "horizontal" work across multiple repos (seems like the latter!)
