### ISSUE TITLE
Setup a zoom meeting for the S3C WG

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/community#630]
Setup a ZOOM or something which doesn't require a specific company / org to do things in the meeting.

currently the GVC works, but a Googler needs to be present to allow non-googlers to enter (which is really lame)
It also requires a googler to record, i think... which is equally lame

Anyone have an account from the community we can use that provides equal access to all community members?

**Comment by afrittoli** [comment]
I setup a Zoom meeting with the Tekton/CDF account.
The meeting is configured to:

- require sign in to join - i.e. a Zoom account is required - this is so we can stop bots from joining 
- automatically recording to the cloud

@xchapter7x would you like to update the invite with this?

---

Tekton is inviting you to a scheduled Zoom meeting.

Topic: S3C WG Meeting
Time: Feb 22, 2022 05:00 PM London
        Every 2 weeks on Tue, until Feb 21, 2023, 27 occurrence(s)
        Feb 22, 2022 05:00 PM
        Mar 8, 2022 05:00 PM
        Mar 22, 2022 05:00 PM
        Apr 5, 2022 05:00 PM
        Apr 19, 2022 05:00 PM
        May 3, 2022 05:00 PM
        May 17, 2022 05:00 PM
        May 31, 2022 05:00 PM
        Jun 14, 2022 05:00 PM
        Jun 28, 2022 05:00 PM
        Jul 12, 2022 05:00 PM
        Jul 26, 2022 05:00 PM
        Aug 9, 2022 05:00 PM
        Aug 23, 2022 05:00 PM
        Sep 6, 2022 05:00 PM
        Sep 20, 2022 05:00 PM
        Oct 4, 2022 05:00 PM
        Oct 18, 2022 05:00 PM
        Nov 1, 2022 05:00 PM
        Nov 15, 2022 05:00 PM
        Nov 29, 2022 05:00 PM
        Dec 13, 2022 05:00 PM
        Dec 27, 2022 05:00 PM
        Jan 10, 2023 05:00 PM
        Jan 24, 2023 05:00 PM
        Feb 7, 2023 05:00 PM
        Feb 21, 2023 05:00 PM
Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://zoom.us/meeting/tJIofuqsrT4oHNMKmcyqk86yIN4f4zZLJcsi/ics?icsToken=98tyKuCuqzIpHteQsh-ARowAGYr4b-jztiVBgo1wtxLmGjFYOlXvH8wWNOZlKvT6

Join Zoom Meeting
https://zoom.us/j/96593435267?pwd=TTNVYUJEQlNzMXlKYjFXcUwzOUZEdz09

Meeting ID: 965 9343 5267
Passcode: 617880
One tap mobile
+13017158592,,96593435267# US (Washington DC)
+13126266799,,96593435267# US (Chicago)

Dial by your location
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 929 205 6099 US (New York)
        +1 253 215 8782 US (Tacoma)
        888 788 0099 US Toll-free
        877 853 5247 US Toll-free
Meeting ID: 965 9343 5267
Find your local number: https://zoom.us/u/acgpXkNaZs

**Comment by lbernick** [comment]
Andrea, just curious, would GVC have the same problem if the meeting owner is a non-Google account (e.g. a gmail account)?

**Comment by afrittoli** [comment]
It wouldn't, but if I recall correctly it would also not support recording

**Comment by bobcatfish** [comment]
@afrittoli @xchapter7x I've updated the calendar event with the zoom meeting details - also @afrittoli it looks like you should have edit permissions on the calendar as well but let me know if that's not the case!

**Comment by pritidesai** [comment]
S3C WG - we have the zoom setup and this can be closed. Thank you!
