### ISSUE TITLE
Exfiltrate `catlin` into its own repository

### ISSUE THREAD

**Issue by PuneetPunamiya** [tektoncd/community#636]
### Feature request

As of now, `catlin` is growing as it's own CLI tool which can be used to manage/interact with tektoncd/catalog. In order to make it available for users there is a need to ship it as a tool which can be used.

## Exfiltrate `catlin` into its own repository

The idea is to move catlin to a separate repository, ie, moving it out of plumbing repository so that it can be managed easily and we can start releasing it as a separate binary.

**Advantages**
* Having it in a separate repo would be easily managed
* We could have a CI setup for the repository 

With additions of more command in catlin like

- `catlin validate` - To validate if the resource follows the Catalog Organization rules
- `catlin lint` - To lint the resources
- `catlin bump` - To bump the version of resource

We can also think of some commands to add in catlin like
- `catlin create` - To create a new resource 
- `catlin diff` - To get the difference between successive versions of task

So it would be nice to have catlin as it's own repo 

## Alternative - Club Catlin with `tkn`

* The other options will be to ship/club catlin within `tkn`

**Advantages**
* This would help the user to not download a separate binary if they have
 `tkn` already installed
* No overhead for Tekton admins - need not to maintain an extra repository

**Disadvantages**
* Managing catlin in `tkn` might be cumbersome

**Comment by bobcatfish** [comment]
Sounds great to me!! 😸

**Comment by vdemeester** [comment]
/assign
I will create the repository this week (tomorrow, wed 16th)

**Comment by vdemeester** [comment]
https://github.com/tektoncd/catlin is live. To close this issue, the following PR needs to be merged
- [ ] https://github.com/tektoncd/community/pull/656
- [ ] https://github.com/tektoncd/plumbing/pull/1022
- [ ] https://github.com/tektoncd/plumbing/pull/1023

**Comment by vdemeester** [comment]
This is now done, we can close.
