### ISSUE TITLE
[Nominations Open] Tekton Most Valuable Contributor Award 2022 🏆

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/community#655]
This issue is to receive nominations for the Tekton Most Valuable Contributor (MVC) Award 2022.

This award recognizes excellence of contributions to the Tekton project, which may be any or a combination of contributions to the project code, documentation, infrastructure as well as advocacy and fostering adoption.

To nominate someone, reply to this issue with the following:

Full name of the person you're nominating
Short description of their contributions to the Tekton project and why they should win.
Nomination Deadline: Tuesday, April 11, 2022

To vote for existing nominations, add emojis to them 🤖 🐱 
Voting Deadline: Monday, April 11, 2022

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by pritidesai** [comment]
I would like to nominate Scott Seaward @sbwsg 🎉 

@sbwsg has been the backbone of the community specially APIs. Scott has a great understanding of the entire code base and never hesitates to share his understanding. He is always ready to help other owners and any new contributors. He makes the entire contribution process an ease for the first time contributors. He has developed/delivered many important features including workspaces, feature gates, remote resolution, etc.

**Comment by pritidesai** [comment]
I would like to nominate Vincent Deemester @vdemeester 

@vdemeester has been the key player in the Pipeline designs, catalog, CLI, and many more. He shares his expertise of building the scalable systems and brings his experience of architecting OpenShift Pipelines in open. Vincent has helped all of us to understand and build the controller for common CI/CD use cases. Thank you Vincent for all the efforts you have put in to build an awesome open source project!

**Comment by zestyroxy** [comment]
### Nomination: Priya Wadhwa @priyawadhwa
She writes great Tekton articles and gives good talks about it, too. I feel like I'm always seeing a Tekton logo with her face next to it on Twitter :) Thank you, Priya!

**Comment by afrittoli** [comment]
+1

>

**Comment by afrittoli** [comment]
> ### Nomination: Priya Wadhwa @priyawadhwa
> She writes great Tekton articles and gives good talks about it, too (and I'm sure there's a lot of dev work behind the scenes). I feel like I'm always seeing a Tekton logo with her face next to it on Twitter :) Thank you, Priya!

`+1`

**Comment by vdemeester** [comment]
@dibyom @afrittoli I will close this as we concluded the vote 👼🏼 
@dibyom will sent a mail to tokten-dev/tekton-users this week
/close
