### ISSUE TITLE
Please fork https://github.com/ahmetb/gen-crd-api-reference-docs into the tektoncd org

### ISSUE THREAD

**Issue by abayer** [tektoncd/community#668]
We'd like to use https://github.com/ahmetb/gen-crd-api-reference-docs for generating API reference docs as part of https://github.com/tektoncd/pipeline/issues/1250, but need a change to that repo (https://github.com/ahmetb/gen-crd-api-reference-docs/pull/43) in order for the tool to work against the pipeline repo. https://github.com/tektoncd/pipeline/pull/4494 has demonstrated that this change works, but I haven't been able to get anywhere with getting the PR to the tool reviewed/merged. So we've concluded that our best option is to fork the repo into the tektoncd org and add the needed change there. Thanks!

cc @afrittoli

**Comment by lbernick** [comment]
Just one thing to look into before doing this: the last release of gen-crd-api-reference-docs was 3 years ago, and the readme states:
```
Today, Kubernetes API https://github.com/kubernetes/kubernetes/pull/71192 provide OpenAPI specs for CRDs (e.g. Knative), therefore the [gen-apidocs](https://github.com/kubernetes-incubator/reference-docs/tree/master/gen-apidocs/generators) generator used by Kubernetes won't work.

Even when Kubernetes API starts providing OpenAPI specs for CRDs, your CRD must have a validation schema (e.g. Knative API doesn't!)
```
it's possible this has changed by now-- we should double check that the k8s api reference docs generator doesn't meet our needs before forking.

**Comment by abayer** [comment]
On that front, https://github.com/tektoncd/pipeline/issues/1461 and the problems getting the OpenAPI schema generator working with Pipeline are relevant...basically, our apis package is a bit weird compared to what "standard" k8s tooling expects, and things tend to barf as a result.

**Comment by abayer** [comment]
Also, while it hasn't had a release in a long time, it is still seeing PRs get merged sporadically, and is used by a good number of projects.

**Comment by vdemeester** [comment]
If it helps, even if it's temporary, I am ok for having a fork in the tektoncd org.

**Comment by afrittoli** [comment]
ok for me

**Comment by afrittoli** [comment]
@tektoncd/governing-board Anyone opposed to this or may we ahead with it?

**Comment by dibyom** [comment]
SGTM!

**Comment by afrittoli** [comment]
@abayer what's the status of this?

**Comment by lbernick** [comment]
Sounds like no objections to creating this fork, which would be the next step needed for generated API reference. I don't have permission-- I think it would need to be one of the org owners (@tektoncd/governing-board)

**Comment by afrittoli** [comment]
https://github.com/tektoncd/ahmetb-gen-crd-api-reference-docs
