### ISSUE TITLE
Owning a new Resource in catalog requires that contributor to be part of org

### ISSUE THREAD

**Issue by vinamra28** [tektoncd/community#685]
As of now whenever there is a contributor in catalog who wants to own a particular resource, they need to be a part of Tekton org first and then only their OWNERS file is validated. Here is the sample PR https://github.com/tektoncd/catalog/pull/967#issuecomment-1096455206 with such situation. This process basically violates the requirements laid down to be a part of [joining the org](https://github.com/tektoncd/community/blob/main/org/README.md#requirements).

Question:
Should we update the requirements for joining the org to include the OWNERS who want to maintain a particular resource?
 OR
Should we change the way of setting up resource OWNERS in catalog? (Basically do some modifications in prow such that it doesn't validate the sub-tree OWNERS file?

/kind question
/cc @tektoncd/governing-board

**Comment by vdemeester** [comment]
> Should we change the way of setting up resource OWNERS in catalog? (Basically do some modifications in prow such that it doesn't validate the sub-tree OWNERS file?

This *cannot* really work very well. Prow and all automation are enforcing this (for being able to assign or put people as reviewers, …).

> Should we update the requirements for joining the org to include the OWNERS who want to maintain a particular resource?

Definitely yes 👼🏼 
Because it is *in the org*, I don't think that's we add people to the org for this. Long term, if/when the Hub allows to register external tekton resources, we could update this process and make sure Tasks in the catalog are maintained by an active group of people, making other resources searchable through the Hub, but maintain by someone else.

**Comment by vinamra28** [comment]
> > Should we change the way of setting up resource OWNERS in catalog? (Basically do some modifications in prow such that it doesn't validate the sub-tree OWNERS file?
> 
> This _cannot_ really work very well. Prow and all automation are enforcing this (for being able to assign or put people as reviewers, …).
> 
> > Should we update the requirements for joining the org to include the OWNERS who want to maintain a particular resource?
> 
> Definitely yes 👼🏼 Because it is _in the org_, I don't think that's we add people to the org for this. Long term, if/when the Hub allows to register external tekton resources, we could update this process and make sure Tasks in the catalog are maintained by an active group of people, making other resources searchable through the Hub, but maintain by someone else.

okay. Will create one to address this.
