### ISSUE TITLE
Using Tekton for CD - dealing with out of order execution

### ISSUE THREAD

**Issue by anikiej** [tektoncd/community#733]
I would like to ask for the recommended solution/best practices for handling the following scenario:

Our Tekton pipeline processes Github repo push events for Continuous Delivery. However, if there are multiple commits happening at once, `PiplineRun`s may finish out of order. Additionally, multiple commits happening at the same time can be collapsed into a single `PipelineRun` (as we only care about the newest commit).

Is there an idiomatic way to express:
- `for` every new Github event - mark it as "pending"
- `if` a `PipelineRun` for a given repo is not yet running:
- - start the pipeline
- `else`
- - wait for that pipeline to finish
- mark the event as "processed"

**Comment by dibyom** [comment]
You might be interested in #716
