### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by hs115488** [tektoncd/community#75]
Where's the code?

**Comment by vdemeester** [comment]
Hi @hs115488, this repository is the community repository, and holds documentation about how the tektoncd community is organized and the rules to follow.

The *code* is, for each components, in its own repository:
- [`tektoncd/pipeline`](https://github.com/tektoncd/pipeline)
- [`tektoncd/cli`](https://github.com/tektoncd/cli)
- [`tektoncd/dashboard`](https://github.com/tektoncd/dashboard)
- [`tektoncd/triggers`](https://github.com/tektoncd/triggers)
- [`tektoncd/operator`](https://github.com/tektoncd/operator)
- [`tektoncd/catalog`](https://github.com/tektoncd/catalog)
- [`tektoncd/experimental`](https://github.com/tektoncd/experimental)

Is your question about having a list of those components in `tektoncd/community` docs ?

/kind question

**Comment by chmouel** [comment]
Thanks @vdemeester 🙇
