### ISSUE TITLE
Does your tekton cat have a name?

### ISSUE THREAD

**Issue by justinabrahms** [tektoncd/community#760]
I got a tekton cat plushie from the open source summit this year. My daughter, now 3, has insisted that the cat's name is Jupo (pronounced joo-poe).

Just curious if your cat has a name already. If it doesn't, maybe it should? :)

**Comment by dibyom** [comment]
Hmmm, excellent question...Not sure if we do at the moment. I think adopting a name is a great idea :)

cc @vdemeester @afrittoli @priyawadhwa @jerop

**Comment by vdemeester** [comment]
Indeed, having a name would help designating the robot cat 🙃. And I do like the "Jupo" suggestion, it's short and simple 👼🏼

**Comment by bendory** [comment]
SGTM

Does this require official adoption by the governance board?

**Comment by bendory** [comment]
/LGTM
/approve
Jupo!

**Comment by bendory** [comment]
Jupo `SGTM` 👍
