### ISSUE TITLE
How does tekton dashboard do authentication and authorization?

### ISSUE THREAD

**Issue by onethefuture** [tektoncd/community#797]
How does tekton do authentication and authorization? The effect it wants to achieve is to give everyone an account, and then everyone's account can only see pipelinerun and taskrun

**Comment by AlanGreene** [comment]
This is described in the Dashboard install docs, see https://tekton.dev/docs/dashboard/install/#access-control for details

Auth is delegated to the Kubernetes API server so you have full access to the usual range of RBAC config and flexibility to use whichever reverse proxy you wish. An `Authorization` header containing a ServiceAccount token can be provided on requests to the Dashboard and it will pass this and other related headers through to the Kubernetes API server, so these can be used to determine which user / ServiceAccount is used for access.

There's a link to a walkthrough with a simple example of deploying oauth2-proxy in front of the Dashboard, as well as some notes on user impersonation.
