### ISSUE TITLE
Project Proposal: The Tekton Hub

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/community#81]
Based on ["part of" the Tekton Catalog and Hub Design](https://docs.google.com/document/d/1pZY7ROLuW47ymZYqUgAbxskmirrmDg2dd8VPATYXrxI/edit?ts=5e559121#heading=h.hqblkoou5o68), I would like to propose having the "tekon hub" project as an experimental project initially.> The Tekton Hub is a web interface where users can both discover existing components and register their components.
> 
> As we iterate on our processes around accepting community owned components, we will follow best practices from Helm and start out with only supporting components in tektoncd/catalog, but once we are happy with the process, we will accept community contributions as well.
> […]
> The code supporting this hub will live in the tektoncd org and the official instance will be available at hub.tekton.dev.

We already started some work on this at Red Hat, and we would like to upstream these into that project (and later one a full-fledge project )

/cc @sthaha @siamaksade @bobcatfish

**Comment by bobcatfish** [comment]
I am a strong :+1: !

**Comment by rakhbari** [comment]
Is this to be built as part of https://tekton.dev ? Isn't that essentially the Tekton Hub?

**Comment by vdemeester** [comment]
Might be related : https://github.com/cncf/hub (https://hub.cncf.io/package/chart/jfrog/pipelines)

**Comment by vdemeester** [comment]
> Is this to be built as part of https://tekton.dev ? Isn't that essentially the Tekton Hub?

It would be published on https://hub.tekton.dev or something like this :wink:

**Comment by rakhbari** [comment]
> 
> 
> > Is this to be built as part of https://tekton.dev ? Isn't that essentially the Tekton Hub?
> 
> It would be published on https://hub.tekton.dev or something like this 😉

If what's being called `the hub` in this proposal is really the Tekton task catalog, then why not just call it that. I'd argue the Tekton Hub is really the main site for tekton.dev. Then you can have a https://catalog.tekton.dev to expose the Tekton task catalog.

**Comment by siamaksade** [comment]
@rakhbari why would hub refer to the Tekton website? Tekton Hub is similar to Helm Hub (https://hub.helm.sh), and Operator Hub (https://www.operatorhub.io/) as the hub for discovering charts and operators respectively.

**Comment by rakhbari** [comment]
> @rakhbari why would hub refer to the Tekton website? Tekton Hub is similar to Helm Hub (https://hub.helm.sh), and Operator Hub (https://www.operatorhub.io/) as the hub for discovering charts and operators respectively.

I'm just going off the "say what you mean, and mean what you say" principle. Somehow "hub" doesn't equal "catalog" to me. If we're following Helm and Operators pattern, then so be it. I just prefer being more specific and calling it what it is. If I'm the only one with this objection, then I defer to the majority decision.

**Comment by sbwsg** [comment]
Saw the demo in the working group today.  Really like the idea of having this start the process of becoming a Tekton project!

**Comment by vdemeester** [comment]
The project is now live and announced :tada: 
https://github.com/tektoncd/hub

/close
