### ISSUE TITLE
Projects that have several, high-profile or well known end-user implementations.

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/community#811]
Tekton is used in production by several vendors as well as end-users.
It is also used as a basis to platforms used in production by end-users.

One interesting example is "Project Trebuchet" at SolarWind, where the company rebuilt their entire build system on top of Tekton in the wake of the Sunburst Hack - see the [SupplyChainSecurityCon keynote from 2021](https://youtu.be/1-tMRxqMwTQ). SolarWinds is a Tekton contributor.

In terms of vendors: 

* IBM provides a seamlessly managed CI/CD experience with Tekton pipelines in [IBM Cloud Continuous Delivery](https://www.ibm.com/cloud/tekton). IBM is a Tekton contributor.

* RedHat builds [OpenShift Pipelines](https://docs.openshift.com/container-platform/4.7/cicd/pipelines/understanding-openshift-pipelines.html), a distribution of Tekton for OpenShift integrated with the OpenShift console. RedHat is a Tekton contributor.

* VMWare includes Tekton as one of its [Application Platform Components](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.2/tap/GUID-scc-ootb-supply-chain-testing.html?hWord=N4IghgNiBcICoFMDWAXA9gOxAXyA). VMWare is a Tekton contributor.

* Relay is a [GA service from Puppet](https://devclass.com/2021/04/07/puppet-relay-ga/) that leverages Tekton. Puppet is a Tekton contributor.

**Comment by dibyom** [comment]
https://shipwright.io/ as well?

**Comment by dibyom** [comment]
And https://github.com/kubeflow/kfp-tekton ?

**Comment by afrittoli** [comment]
Shipwright and ktp-tekton are great for C8 - platform for other projects.
This is about end-users implementations.

**Comment by afrittoli** [comment]
IBM is also a very large end-user of Tekton: IBM Provides a large scale Tekton-as-a-service offering to its development teams.

**Comment by afrittoli** [comment]
I will add new end-users implementation as they become available.
SolarWind and IBM are considered enough to satisfy this requirement.
