### ISSUE TITLE
 New org for tekton experiments?

### ISSUE THREAD

**Issue by dibyom** [tektoncd/community#835]
tektoncd/experimental can be hard to work with - this is the only monorepo style repo we have and it contains a bunch of inactive experiments. A failing test in one inactive project means we cannot merge a PR in another project (https://github.com/tektoncd/experimental/pull/896)

Most of our CI is optimized for single repo use cases not mono repos. One option is we create a `tektoncd-experimental` org and create new experiments as separate repos in that org. 

There is some initial overhead with setting up a new org but I think it's still probably worth it:
1. Setting up Prow/Tekton for CI
2. Setting up Peribolos for org administration
3. Update docs to mention this as the new org for experiments
4. Potentially migrate some of the active experiments from tektoncd/experimental

@tektoncd/governing-board what do you think?

**Comment by afrittoli** [comment]
It sounds like a good idea. If you could prepare a detailed plan about what would be required, I'd be happy to help implementing it.

**Comment by vdemeester** [comment]
@dibyom the idea is that this would *hold* experiments done from some tekton community members and could (or not) be promoted at some point right ? It sounds very similar to https://github.com/knative-sandbox/ I guess 🙃.

I do feel this is extra work that might not necessarily needed, aka compared to have the experiment in one repository or in a non-tekton organization, but I don't feel too strongly about that as well. 

So, it sounds like a good idea yes 👍🏼

**Comment by dibyom** [comment]
> @dibyom the idea is that this would hold experiments done from some tekton community members and could (or not) be promoted at some point right ? It sounds very similar to https://github.com/knative-sandbox/ I guess 🙃.

Yup! exactly!

> I do feel this is extra work that might not necessarily needed, aka compared to have the experiment in one repository or in a non-tekton organization, but I don't feel too strongly about that as well.

You might be right though I do feel that working in experimental can be bit more challenging due to having to fit into the monorepo pattern. I'll try to scope out the things we need to do to get a new org running

**Comment by dibyom** [comment]
As a first step, I picked up the tektoncd-experiments org

**Comment by jerop** [comment]
@lbernick this is related to https://github.com/tektoncd/community/pull/956 (but not a blocker, just wanted to make sure you're aware)

**Comment by dibyom** [comment]
> There's probably going to be a lot of work for setting up CI - we don't have a great story for onboarding new projects, but perhaps this is a way to drive this dogfooding?

@QuanZhang-William recently setup org management and CI for the new catalog org...maybe we could write up a guide based on that experience?

**Comment by QuanZhang-William** [comment]
> > There's probably going to be a lot of work for setting up CI - we don't have a great story for onboarding new projects, but perhaps this is a way to drive this dogfooding?
> 
> @QuanZhang-William recently setup org management and CI for the new catalog org...maybe we could write up a guide based on that experience?

Yeah I can definitely help documenting the process of setting up new orgs. I think the org management (Prow) part should be very similar for all the orgs, but the CI setup can be quite different based on the test infrastructure and tests themselves.

But I can at least write out the CI settings for catalog org as an example.
