### ISSUE TITLE
wlynch govboard access

### ISSUE THREAD

**Issue by wlynch** [tektoncd/community#897]
Tracking issue for getting access to govboard resources:

[When someone joins the governing board](https://github.com/tektoncd/community/blob/main/governance.md#changes-to-governing-board):

- [x] They should be added to [the list of current governing board members](#current-members)
- [x] They should be granted [the permissions given them as members of the governing board](#permissions-and-access)
- [x] They will be added to the `#governance-private` and `#governance` [slack](contact.md#slack) channels
- [x] They will be added as facilitators to [the Governing Board and Community meeting](https://github.com/tektoncd/community/blob/main/working-groups.md#governing-board--community)
- [x] They will be added as managers to [the Tekton community Google Drive](https://github.com/tektoncd/community/blob/main/contact.md#shared-drive)
- [x] They will be added as admins to [the tektoncd GitHub org](https://github.com/tektoncd/community/blob/main/org/org.yaml)
- [x] They will be added as team members to the `governing-board` team in [the tektoncd GitHub org](https://github.com/tektoncd/community/blob/main/org/org.yaml)
- [x] They will be added as owners to [the community repo](https://github.com/tektoncd/community/blob/main/OWNERS)
- [x] They will be added to these mailing lists as owners:
  - [`tekton-governance`](https://groups.google.com/g/tekton-governance)
  - [`tekton-nominations`](https://groups.google.com/g/tekton-nominations)
  - [`tekton-dev`](https://groups.google.com/g/tekton-dev)
  - [`tekton-users`](https://groups.google.com/g/tekton-users)
  - [`tekton-code-of-conduct`](https://groups.google.com/g/tekton-code-of-conduct)

**Comment by wlynch** [comment]
cc @tektoncd/governing-board

**Comment by dibyom** [comment]
@wlynch you should an invite to join the tekton-governance and tekton-nominations google groups

for the tekton-code-of-conduct group, it looks like the current owners are @bobcatfish @priyawadhwa and @jerop - could one of you give Billy access (and also make the other current gov board members owners?)

**Comment by wlynch** [comment]
Thanks @dibyom! Could I also get audit log / billing account access on the GCP projects? (owner also works if that's easier) 🙏

**Comment by dibyom** [comment]
done! (I gave folder-admin permissions on the Tekton Project folder that contains all Tekton projects to all gov board members)

**Comment by bobcatfish** [comment]
@wlynch you should be invited to tekton-code-of-conduct as well and now @dibyom @vdemeester @afrittoli should be owners as well (not sure what happened there??)
