### ISSUE TITLE
[Nominations Open] Most Valuable Tekton Contributor 2023 🏆

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/community#959]
This issue is to receive nominations for the Most Valuable Tekton Contributor 2023. 

This award recognises excellence of contributions to the Tekton project, which may be any or a combination of contributions to the project code, documentation, and infrastructure as well as advocacy and fostering adoption.

To nominate someone, please use the linked Google form (TBD).
If you'd prefer to not use a Google form, please send an email to tekton-nominations@googlegroups.com

1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

Nomination Deadline: Friday, March 3, 2023

Please note: Last year's winner, Vincent Demeester, cannot win the award for Most Valuable Tekton Contributor again this year.

More details are available here https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md

**Comment by wlynch** [comment]
Consolidating in https://github.com/tektoncd/community/issues/961
