### ISSUE TITLE
Proposal: Add Tekton Katacoda Repo

### ISSUE THREAD

**Issue by popcor255** [tektoncd/community#96]
This issue is to discuss if the Katacoda's in the tektoncd website should be a part of the tekton org.

### Background
The way you create a Katacoda courses is by creating a repo with each course being in a seperate folder. Katacoda will give you a webhook that you must add in order for the courses to sync.
[How to create Katacoda Course](https://www.katacoda.com/profile/create-first-scenario/cli)

The link for the Katacoda on the website is owned by @ncskier. https://katacoda.com/ncskier/scenarios/tekton-dashboard

Minikube allows us to create more Katacoda coursers; however, is there is not a process to contribute to these courses. I think have these coursers under the Tekton org would be a good idea.

**Comment by bobcatfish** [comment]
Hey @popcor255 ! Thanks for making the proposal :D Quick question, does katacoda allow you to make tutorials as subdirectories of existing repos? If so, I'm wondering about the pros/cons of having a folder within tektoncd/website vs. having a separate repo for these

**Comment by popcor255** [comment]
Hello @bobcatfish. Hey you 100% correction. I start digging into ways to do that. I found a katacoda that showed me how to exactly with katacoda.
Very Meta. 🤯 
[How to make Katacoda course](https://katacoda.com/scenario-examples/scenarios/create-course)
