### ISSUE TITLE
[Nominations Open] Tekton Security MVP 2023 🏆

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/community#960]
This issue is to receive nominations for the Tekton Security MVP 2023. 

This award is presented to an individual most consistently providing excellent security reports or resolving security issues.

To nominate someone, please use the linked Google form (TBD).
If you'd prefer to not use a Google form, please send an email to [tekton-nominations@googlegroups.com](mailto:tekton-nominations@googlegroups.com)

1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

Nomination Deadline: Friday, March 3, 2023

More details are available here https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md

**Comment by wlynch** [comment]
Consolidating in https://github.com/tektoncd/community/issues/961
